---
- name: Install Python 3
  hosts: mx
  become: true
  become_method: doas
  gather_facts: no
  tasks:
    - name: which python3
      raw: which python3
      changed_when: false
      failed_when: false
      register: which_python3

    - name: pkg_add python3
      when: which_python3.rc == 2
      raw: pkg_add python3

- name: IPv6
  hosts: mx
  become: true
  become_method: doas
  tasks:
    - name: '/etc/hostname.vio0: inet6'
      lineinfile:
        path: /etc/hostname.vio0
        regexp: '^inet6 '
        line: 'inet6 {{ ipv6_addr }} 64'
      register: hostname_vio0

    - name: /etc/mygate
      copy:
        dest: /etc/mygate
        content: |
          fe80::1%vio0
      register: etc_mygate

    - name: sh /etc/netstart
      when: hostname_vio0.changed or etc_mygate.changed
      shell: sh /etc/netstart

- name: Security
  hosts: mx
  become: true
  become_method: doas
  tasks:
    - name: Lock root login
      user:
        name: root
        password: '*************'
