---
- name: Mail
  hosts: mx
  become: true
  become_method: doas
  tasks:
    - include_tasks: ../../tasks/letsencrypt.yml
      vars:
        domain: mx.allianzfreidemrus.de
        intern: true
        rcctl: restart smtpd

    - name: Install opensmtpd-filter-dnsbl
      openbsd_pkg:
        name: opensmtpd-filter-dnsbl

    # Redis

    - name: Install redis
      openbsd_pkg:
        name: redis

    - name: '/etc/redis/redis.conf: unixsocket'
      blockinfile:
        path: /etc/redis/redis.conf
        block: |
          unixsocket /var/run/redis/redis.sock
          unixsocketperm 770
      register: redis_conf

    - name: '/etc/redis/redis.conf: port'
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^port '
        line: port 0
      register: redis_conf_port

    - name: Stop redis
      when: redis_conf.changed or redis_conf_port.changed
      service:
        name: redis
        state: stopped

    - name: Start redis
      service:
        name: redis
        state: started
        enabled: true

    # rspamd

    - name: Install rspamd
      openbsd_pkg:
        name: rspamd-3.4p2

    - name: Disable /etc/rspamd/local.d/...
      loop:
        - greylist.conf
        - worker-proxy.inc
        - worker-controller.inc
      copy:
        dest: '/etc/rspamd/local.d/{{ item }}'
        content: enabled = false;
      register: rspamd_disable

    - name: Invite _rspamd to _redis
      user:
        name: _rspamd
        create_home: false
        append: true
        groups:
          - _redis
      register: rspamd_group_redis

    - name: /etc/rspamd/local.d/redis.conf
      copy:
        dest: /etc/rspamd/local.d/redis.conf
        content: servers = "/var/run/redis/redis.sock";
      register: rspamd_redis

    - name: /etc/rspamd/override.d/worker-normal.inc
      copy:
        dest: /etc/rspamd/override.d/worker-normal.inc
        content: bind_socket = "/var/rspamd/worker-normal.sock owner=_smtpd mode=0600";
      register: rspamd_worker_normal

    - name: Stop rspamd
      when: >-
        rspamd_group_redis.changed
        or rspamd_disable.changed
        or rspamd_redis.changed
        or rspamd_worker_normal.changed
      service:
        name: rspamd
        state: stopped

    - name: Start rspamd
      service:
        name: rspamd
        state: started
        enabled: true

    - name: Install opensmtpd-filter-rspamd
      openbsd_pkg:
        name: opensmtpd-filter-rspamd

    # qdgrey

    - name: Install go
      openbsd_pkg:
        name: go

    - name: /usr/local/opensmtpd-filter-qdgrey
      copy:
        dest: /usr/local
        src: ../../subtrees/opensmtpd-filter-qdgrey
      register: qdgrey_src

    - name: Remove /usr/local/libexec/smtpd/filter-qdgrey
      when: qdgrey_src.changed
      file:
        path: /usr/local/libexec/smtpd/filter-qdgrey
        state: absent

    - name: go build -o /usr/local/libexec/smtpd/filter-qdgrey
      shell: go build -o /usr/local/libexec/smtpd/filter-qdgrey .
      args:
        chdir: /usr/local/opensmtpd-filter-qdgrey
        creates: /usr/local/libexec/smtpd/filter-qdgrey
      register: qdgrey_bin

    # SMTP

    - name: /etc/mail/mailname
      copy:
        dest: /etc/mail/mailname
        content: |
          mx.allianzfreidemrus.de
      register: mail_mailname

    - name: /etc/mail/vdomains
      copy:
        dest: /etc/mail/vdomains
        content: |
          allianzfreidemrus.de
      register: mail_vdomains

    - name: /etc/mail/rt.d
      file:
        path: /etc/mail/rt.d
        state: directory

    - name: /etc/mail/rt.d/...
      loop:
        - action: correspond
          queue: General
        - action: comment
          queue: General
        - action: correspond
          queue: IT
        - action: comment
          queue: IT
      copy:
        dest: '/etc/mail/rt.d/{{ item.action }}-{{ item.queue }}'
        mode: '0755'
        content: |
          #!/bin/ksh
          exec /usr/local/bin/rt-mailgate --action {{ item.action
          }} --queue {{ item.queue }} --url http://localhost:8080/

    - name: /etc/mail/vusers
      copy:
        dest: /etc/mail/vusers
        content: |
          info@allianzfreidemrus.de  |/etc/mail/rt.d/correspond-General
          rtx@allianzfreidemrus.de  |/etc/mail/rt.d/comment-General
          it@allianzfreidemrus.de  |/etc/mail/rt.d/correspond-IT
          rtx-it@allianzfreidemrus.de  |/etc/mail/rt.d/comment-IT
          postmaster@allianzfreidemrus.de  |/etc/mail/rt.d/correspond-IT
      register: mail_vusers

    - name: /etc/mail/aliases
      blockinfile:
        path: /etc/mail/aliases
        block: |
          root:  |/etc/mail/rt.d/correspond-IT
      register: mail_aliases

    - name: /etc/mail/smtpd.conf
      copy:
        dest: /etc/mail/smtpd.conf
        src: smtpd.conf
      register: smtpd_conf

    - name: Stop smtpd
      when: >-
        mail_mailname.changed
        or mail_vdomains.changed
        or mail_vusers.changed
        or mail_aliases.changed
        or smtpd_conf.changed
      service:
        name: smtpd
        state: stopped

    - name: Start smtpd
      service:
        name: smtpd
        state: started

    - name: Enable smtpd
      lineinfile:
        path: /etc/rc.conf.local
        regexp: '^smtpd_flags='
        line: smtpd_flags=
